# Generated by OpenTofu import
# This is your imported server configuration
resource "ovh_dedicated_server" "talos01" {
  ovh_subsidiary = var.ovh_subsidiary
  monitoring     = false
  state          = "ok"
  
  # Optional attributes - uncomment to manage them
  # boot_id        = 230242
  # display_name   = "My Server Name"
  # rescue_ssh_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM6SQjc9vOK3yZ6rxrTfeiJ+HaUZvNlHwmcNcJCU1PDS msawicki@ms-c1"
}
